[package]
name = "in_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
open = "5.3"
chrono = "0.4"
once_cell = "1"
futures = "0.3"
scraper = "0.23"
indicatif = "0.18"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
